name: sample_pubspec
description: A sample application
dependencies:
  unittest: 0.3.7+6
  dart_rtc_client:
    git: git://github.com/samiy-xx/dart_rtc_client.git
  browser: any
  dart_rtc_common:
    git: git://github.com/samiy-xx/dart_rtc_common.git
